"""Scheduler and admin UI add-on for OEDS."""

from oeds_scheduler_ui.interfaces import (
    CrawlerRegistry,
    CrawlerSpec,
    OedsCrawlerConfig,
    SchedulerJob,
    load_crawler_target,
    merge_crawler_registries,
    normalize_crawler_config,
    registry_from_spec_strings,
    run_crawler_instance,
)
from oeds_scheduler_ui.distribution import load_inventory, registries_from_inventory
from oeds_scheduler_ui.discovery import (
    DiscoveryIssue,
    DiscoveryResult,
    discover_crawler_specs,
)
from oeds_scheduler_ui.config import file_signature, load_scheduler_config
from oeds_scheduler_ui.application import (
    SchedulerApplication,
    SchedulerApplicationSnapshot,
    format_application_summary,
)
from oeds_scheduler_ui.daemon import SchedulerDaemon
from oeds_scheduler_ui.factory import (
    CONSTRUCTOR_CRAWLER_NAME_CONFIG,
    CONSTRUCTOR_SCHEMA_NAME_CONFIG,
    CONSTRUCTOR_SCHEMA_NAME_ONLY,
    CONSTRUCTOR_UNKNOWN,
    ConstructorAudit,
    ConstructorPlan,
    CrawlerFactory,
    audit_crawler_spec,
    module_file_from_spec,
)
from oeds_scheduler_ui.planner import (
    CrawlerJobConfig,
    SchedulerJobPlan,
    SchedulerPlanIssue,
    SchedulerPlanResult,
    apply_default_config,
    build_scheduler_job_plans,
    expand_crawler_job_configs,
    merge_job_config,
)
from oeds_scheduler_ui.runtime import (
    CrawlerJobQueue,
    CrawlerJobRunner,
    CrawlerRunResult,
    PostRunCommandResult,
    QueuedCrawlerJob,
    ScheduledCrawlerJob,
    execute_post_command,
    execute_python_script,
    lock_keys_from_plan,
    run_ready_jobs,
    scheduled_job_from_plan,
)
from oeds_scheduler_ui.service import (
    CronConverterSchedule,
    ScheduleAdapter,
    ScheduleFactory,
    ScheduledPlan,
    SchedulerService,
    SchedulerServiceIssue,
    cron_schedule_factory,
)

__all__ = [
    "CONSTRUCTOR_CRAWLER_NAME_CONFIG",
    "CONSTRUCTOR_SCHEMA_NAME_CONFIG",
    "CONSTRUCTOR_SCHEMA_NAME_ONLY",
    "CONSTRUCTOR_UNKNOWN",
    "CronConverterSchedule",
    "CrawlerFactory",
    "CrawlerJobConfig",
    "CrawlerJobQueue",
    "CrawlerJobRunner",
    "CrawlerRegistry",
    "CrawlerRunResult",
    "CrawlerSpec",
    "ConstructorAudit",
    "ConstructorPlan",
    "DiscoveryIssue",
    "DiscoveryResult",
    "OedsCrawlerConfig",
    "PostRunCommandResult",
    "QueuedCrawlerJob",
    "ScheduleAdapter",
    "ScheduleFactory",
    "SchedulerJob",
    "SchedulerJobPlan",
    "SchedulerPlanIssue",
    "SchedulerPlanResult",
    "SchedulerApplication",
    "SchedulerApplicationSnapshot",
    "SchedulerDaemon",
    "SchedulerService",
    "SchedulerServiceIssue",
    "ScheduledCrawlerJob",
    "ScheduledPlan",
    "apply_default_config",
    "audit_crawler_spec",
    "build_scheduler_job_plans",
    "cron_schedule_factory",
    "discover_crawler_specs",
    "execute_post_command",
    "execute_python_script",
    "expand_crawler_job_configs",
    "file_signature",
    "format_application_summary",
    "lock_keys_from_plan",
    "load_scheduler_config",
    "load_crawler_target",
    "load_inventory",
    "merge_job_config",
    "merge_crawler_registries",
    "module_file_from_spec",
    "normalize_crawler_config",
    "registries_from_inventory",
    "registry_from_spec_strings",
    "run_ready_jobs",
    "run_crawler_instance",
    "scheduled_job_from_plan",
]
